### ISSUE TITLE
Give to mod moderation tools 

### ISSUE THREAD

**Issue by ghost** [Tupperbox/TupperboxLegacy#124]
Sometimes some peoples abuse of the bot by using it to anonymously insult other peoples that's why I think it could be good if you add a command to check who possess which proxy to help mod by using, for example, the name of the proxy in the Guild

**Comment by greysdawn** [comment]
This is already possible with `tul!showuser` and the ❓ reaction, both of which should be mentioned in the bot's help command. The first one will show who sent the last proxied message in a channel, so if the message is higher up, you can reply to the message with the command to see who sent it

Like this:
![image](https://user-images.githubusercontent.com/29555267/125205495-81ed3680-e250-11eb-9431-0fd56ec6058d.png)
